AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: Sample EC2 Instance with EBS Volume and Security Group
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small, t2.medium, t2.large, t3.micro, t3.small, t3.medium, t3.large, m5.large, m5.xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  VPC:
    Type: AWS::EC2::VPC::Id
  PublicSubnet:
    Type: AWS::EC2::Subnet::Id
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'LatestAmiId'
      BlockDeviceMappings:
        - DeviceName: "/dev/sdm"
          Ebs:
            VolumeType: "gp2"
            DeleteOnTermination: "true"
            VolumeSize: "10"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: "InstanceSecurityGroup"
          SubnetId:
            Ref: "PublicSubnet"
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref 'SSHLocation'
      VpcId: !Ref 'VPC'
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, AvailabilityZone]
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicDnsName]
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]
EOF
aws:
   s3-bucket-name: dev-securin-pipeline
   access-key: ASIAXZQOO5CYVCQLIVKG
   secret-key: xcwdIFb71LCGjUsjB/Qc5xk0tX37H8Pr3SSzUVjI
   seller.session: IQoJb3JpZ2luX2VjEJ7//////////wEaCXVzLXdlc3QtMiJGMEQCIAFeNjeD0qmiDGgW6j7p3bu0MpP+5prPxlIXf2sV4+cCAiBRZUy8u53L5ueXcZnIDn6eER2dVTOnfrDedwORMfoGcyqmAwjX//////////8BEAAaDDUzNTgyNzUwNzM3NyIM2qCEphWK72nfBtV3KvoCKeNLJHv04YUl2hAwVxZWuXWX6djJOAdwvYvBbMPXSNQAB4YQuCCrZKlOcv/yBMPyHlghEf57oob7xnlPOOf8rb3zfh0I3AFPQyEkVJE7K5pemmbccEEjrDkbnFMrJZ3Y7UJkewdvcHKconiC/mPKVEeMiOpsHQojH3gYldEE8n9mL+qXOV4MVuyw6LW/1nXpoGjjJ/a37tiH+d19tAWxwWBwl7gBrkvSLWr1Q4Lzcm74nbKSfkulwwiBO/QZ+TDXM2mbLy2WRGzViAcIcbNuOogIhJroxntXM9nmd4oAtwEmP2YjCrDIPQmkRnh8V+3cLdHxqbT6Nh/IAvfwO+ZMfCJCq5zTvLWLOLGNs2FUcRE+Rj/i5ED9KpcU82yN/3O7y10aBqk33+ecCHwJqTxooQlbxj5vT6upR7Yg9OX8Y77qQyRqSZhtN9I854aEOkR8lnlbUGCiH3wM9NaJStBxyYFUxJoKWu/VaHv9KVIjW6KEREfhACPOLL+GMOrhuIkGOqcBi84Rou2/e7Td0Z+2GZH/Zrcetpe8yw6OEoUDXaiknUt4GfQLRcAqj3C6c6x4GIxMk4Bas3hStLhBlovWhwJn/ptIH++aRBYC75nLJ264YJ3f3D8+r8InnHn7F8tO9GRuq+27nKn4mv9qS+xRyKuHEnv/DnaOqLl46ffjjWvw57dpuofDJycirqyTIn7hutabB4BMXGzovQ98hG1azTincyZZEK/2IL8=
   seller.role-arn: arn:aws:iam::535827507377:role/shiftleft-ecr-role
